import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from '@ecomm/ui/toaster';
import { I18nProviderClient } from '@/locales/client';
import { Header } from '@/components/header';
import { getStaticParams } from '@/locales/server';
import { setStaticParamsLocale } from 'next-international/server';
import { notFound } from 'next/navigation';
import { Suspense } from 'react';
import { Footer } from '@/components/footer';
import { getStoreByLocale } from '@/features/store/services/queries';
import { StoreProvider } from '@/features/store/providers/store-provider';
import { AVAILABLE_LOCALES, type Locale } from '@ecomm/lib/locale-helper';
import { GoogleTagManager } from '@next/third-parties/google';
import { clientEnv } from '@/env/client';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function Providers({
  locale,
  children,
}: {
  locale: string;
  children: React.ReactNode;
}) {
  const store = await getStoreByLocale(locale);

  return (
    <I18nProviderClient locale={locale}>
      <StoreProvider store={store.success ? store.data : null}>
        {children}
      </StoreProvider>
    </I18nProviderClient>
  );
}

export const generateStaticParams = () => {
  return getStaticParams();
};

export default async function RootLayout({
  params,
  children,
  cart,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
  cart: React.ReactNode;
}>) {
  const locale = (await params).locale;
  if (!AVAILABLE_LOCALES.includes(locale as Locale)) return notFound();

  setStaticParamsLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <GoogleTagManager gtmId={clientEnv.NEXT_PUBLIC_GTM_ID} />
        <NuqsAdapter>
          <Providers locale={locale}>
            <div>
              <Header />
              <main className="min-h-[350px]">
                {cart && cart}
                {children}
              </main>
              <Suspense>
                <Footer />
              </Suspense>
            </div>
            <Toaster />
          </Providers>
        </NuqsAdapter>
      </body>
    </html>
  );
}
