import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from '@ecomm/ui/toaster';
import { WindowInfoProvider } from '@faceless-ui/window-info';
import { I18nProviderClient } from '@/locales/client';
import { AVAILABLE_LOCALES } from '@/lib/utils/locale-helper';
import { Header } from '@/components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function Providers({
  locale,
  children,
}: {
  locale: string;
  children: React.ReactNode;
}) {
  return <I18nProviderClient locale={locale}>{children}</I18nProviderClient>;
}

export const generateStaticParams = () => {
  return AVAILABLE_LOCALES.map((locale) => ({ locale }));
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {
  const locale = (await params).locale;

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NuqsAdapter>
          <WindowInfoProvider
            breakpoints={{
              s: '(min-width: 640px)',
              m: '(min-width: 768px)',
              l: '(min-width: 1024px)',
              xl: '(min-width: 1280px)',
            }}
          >
            <Providers locale={locale}>
              <Header />
              {children}
              <Toaster />
            </Providers>
          </WindowInfoProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
