import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from '@ecomm/ui/toaster';
import { I18nProviderClient } from '@/locales/client';
import { Header } from '@/components/header';
import { getStaticParams } from '@/locales/server';
import { setStaticParamsLocale } from 'next-international/server';
import { AVAILABLE_LOCALES, type Locale } from '@/lib/utils/locale-helper';
import { notFound } from 'next/navigation';
import { Suspense } from 'react';
import { Footer } from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function Providers({
  locale,
  children,
}: {
  locale: string;
  children: React.ReactNode;
}) {
  return <I18nProviderClient locale={locale}>{children}</I18nProviderClient>;
}

export const generateStaticParams = () => {
  return getStaticParams();
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {
  const locale = (await params).locale;
  if (!AVAILABLE_LOCALES.includes(locale as Locale)) return notFound();

  setStaticParamsLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NuqsAdapter>
          <Providers locale={locale}>
            <div>
              <Header />
              <main className="min-h-[350px]">{children}</main>
              <Suspense>
                <Footer />
              </Suspense>
            </div>
            <Toaster />
          </Providers>
        </NuqsAdapter>
      </body>
    </html>
  );
}
